repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]

  - repo: https://github.com/mvdan/sh
    rev: v3.5.1
    hooks:
      - id: shfmt
        name: shfmt
        entry: shfmt -w -i 2 -ci
        language: system
        types: [shell]