#cloud-config
users:
  - default
  - name: ubuntu
    gecos: Ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/zsh
package_update: true
package_upgrade: true
packages:
  - zsh
  - unzip
  - stow
  - neovim
  - nushell
  - git
  - curl
runcmd:
  - chsh -s /bin/zsh ubuntu
  - curl -s https://ohmyposh.dev/install.sh | bash -s
  - sudo snap install nushell --classic
  # DOTFILES_REPO env var should be used here instead of hardcoded URL
  - git clone $DOTFILES_REPO /home/ubuntu/dotfiles
  - cp /home/ubuntu/dotfiles/.zshrc /home/ubuntu/
  - cp /home/ubuntu/dotfiles/.oh-my-posh-theme.json /home/ubuntu/
  - echo 'exec zsh' >> /home/ubuntu/.bashrc