#!/usr/bin/env bash
# Interactive setup wizard for dotfiles
# This script asks the user which optional components they want to enable,
# writes the choices to dotfiles.yml and then runs the main install script.

set -euo pipefail

CONFIG_FILE="dotfiles.yml"

# ----------------------------------------------------------------------
# Helper: ask a yes/no question.
#   $1 - Prompt text
#   $2 - Default answer (Y or N)
# Returns 0 for yes, 1 for no.
# ----------------------------------------------------------------------
ask() {
    local prompt="$1"
    local default="${2:-N}"
    local response

    while true; do
        if [[ "$default" == "Y" ]]; then
            read -rp "$prompt [Y/n]: " response
            response=${response:-Y}
        else
            read -rp "$prompt [y/N]: " response
            response=${response:-N}
        fi

        case "$response" in
            [Yy]* ) return 0 ;;
            [Nn]* ) return 1 ;;
            * ) echo "Please answer yes or no." ;;
        esac
    done
}

# ----------------------------------------------------------------------
# Define the optional components and their corresponding YAML keys.
# ----------------------------------------------------------------------
declare -A COMPONENTS=(
    ["VSCode extensions"]="vscode_extensions"
    ["tmux plugins"]="tmux_plugins"
    ["Optional tools"]="optional_tools"
)

# ----------------------------------------------------------------------
# Gather user selections.
# ----------------------------------------------------------------------
declare -A SELECTIONS
for name in "${!COMPONENTS[@]}"; do
    if ask "Enable $name?" Y; then
        SELECTIONS["$name"]=true
    else
        SELECTIONS["$name"]=false
    fi
done

# ----------------------------------------------------------------------
# Ensure a config file exists.
# ----------------------------------------------------------------------
if [[ ! -f "$CONFIG_FILE" ]]; then
    {
        echo "# Generated by dotfiles wizard"
        for key in "${COMPONENTS[@]}"; do
            echo "$key: false"
        done
    } > "$CONFIG_FILE"
fi

# ----------------------------------------------------------------------
# Update the YAML configuration.
# Prefer yq if it is installed; otherwise fall back to simple sed.
# ----------------------------------------------------------------------
if command -v yq >/dev/null 2>&1; then
    for name in "${!COMPONENTS[@]}"; do
        yaml_key="${COMPONENTS[$name]}"
        yaml_val="${SELECTIONS[$name]}"
        # yq expects true/false without quotes
        yq eval ".$yaml_key = $yaml_val" -i "$CONFIG_FILE"
    done
else
    # Portable sed implementation (POSIX compatible)
    for name in "${!COMPONENTS[@]}"; do
        yaml_key="${COMPONENTS[$name]}"
        yaml_val="${SELECTIONS[$name]}"
        if grep -qE "^$yaml_key:" "$CONFIG_FILE"; then
            # Replace existing line
            sed -i.bak "s/^$yaml_key:.*/$yaml_key: $yaml_val/" "$CONFIG_FILE"
        else
            # Append if missing
            echo "$yaml_key: $yaml_val" >> "$CONFIG_FILE"
        fi
    done
    # Clean up backup if created
    [ -f "${CONFIG_FILE}.bak" ] && rm -f "${CONFIG_FILE}.bak"
fi

echo "✔ Configuration written to $CONFIG_FILE"

# ----------------------------------------------------------------------
# Run the main installation script.
# ----------------------------------------------------------------------
if [[ -x "./install.sh" ]]; then
    echo "Running install.sh..."
    ./install.sh
else
    echo "Error: install.sh not found or not executable."
    exit 1
fi