gui:
  editor: nvim
  pager: delta --dark --paging=never
  theme:
    lightTheme: false

keybinding:
  universal:
    confirm: <c-j>
    cancel: <c-k>
    return: <c-m> # default Enter binding preserved
  files:
    push: <c-p>

os:
  editCommand: 'nvim {{filename}}'
  openCommand: 'open {{filename}}'

update:
  method: prompt

git:
  paging:
    externalDiffCommand: 'delta --dark'

customCommands:
  - key: 'b'
    context: 'files'
    command: 'gh repo view --web'
    description: 'Open repo in browser'
    subprocess: true
