# set true color
set-option -sa terminal-overrides ",xter*:Tc"

# set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# vim-style copy mode
set-window-option -g mode-keys vi
bind [ copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection \; set-option -p -q @zsh_vi_mode VISUAL
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy" \; set-option -p -q @zsh_vi_mode INSERT
bind-key -T copy-mode-vi Escape send-keys -X cancel \; set-option -p -q @zsh_vi_mode INSERT
bind-key -T copy-mode-vi q send-keys -X cancel \; set-option -p -q @zsh_vi_mode INSERT
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dreamsofcode-io/catppuccin_tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# tmux-resurrect settings
set -g @resurrect-capture-pane-contents 'on'

# tmux-continuum settings
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

run '~/.tmux/plugins/tpm/tpm'

# mode indicator
set -g status-interval 1
set -g status-left-length 60
set -g @zsh_vi_mode INSERT
set -g status-left '#[fg=colour232,bg=#{?selection_present,colour213,#{?pane_in_mode,colour220,#{?#{==:#{@zsh_vi_mode},NORMAL},colour39,colour76}}},bold] #{?selection_present,VISUAL,#{?pane_in_mode,NORMAL,#{@zsh_vi_mode}}} #[default] #S '
