# set true color
set-option -sa terminal-overrides ",xter*:Tc"

# set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# vim-style copy mode
set-window-option -g mode-keys vi
bind [ copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection \; set-option -p -q @zsh_vi_mode VISUAL
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy" \; set-option -p -q @zsh_vi_mode INSERT
bind-key -T copy-mode-vi Escape send-keys -X cancel \; set-option -p -q @zsh_vi_mode INSERT
bind-key -T copy-mode-vi q send-keys -X cancel \; set-option -p -q @zsh_vi_mode INSERT
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dreamsofcode-io/catppuccin_tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# tmux-resurrect settings
set -g @resurrect-capture-pane-contents 'on'

# tmux-continuum settings
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# status bar
set -g status-interval 1
set -g status-left-length 60
set -g status-right-length 100
set -g status-position bottom
set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g message-style "bg=#313244,fg=#cdd6f4"
set -g mode-style "bg=#f5c2e7,fg=#1e1e2e"

set -g window-status-separator ""
set -g window-status-format " #[fg=#6c7086,bg=#1e1e2e]#I:#W "
set -g window-status-current-format "#[fg=#1e1e2e,bg=#89b4fa,bold] #I:#W #[fg=#89b4fa,bg=#1e1e2e]"
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#89b4fa"

set -g @zsh_vi_mode INSERT
set -g status-left '#[fg=#1e1e2e,bg=#{?selection_present,#f5c2e7,#{?pane_in_mode,#f9e2af,#{?#{==:#{@zsh_vi_mode},NORMAL},#89b4fa,#a6e3a1}}},bold] #{?selection_present,VISUAL,#{?pane_in_mode,NORMAL,#{@zsh_vi_mode}}} #[fg=#{?selection_present,#f5c2e7,#{?pane_in_mode,#f9e2af,#{?#{==:#{@zsh_vi_mode},NORMAL},#89b4fa,#a6e3a1}}},bg=#1e1e2e] #S '
set -g status-right '#[fg=#6c7086,bg=#1e1e2e] %H:%M #[fg=#cba6f7]#h '

run '~/.tmux/plugins/tpm/tpm'
